# Generated by Django 4.0.4 on 2024-02-01 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings', '0002_remove_accounttype_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttype',
            name='name',
        ),
        migrations.AddField(
            model_name='accounttype',
            name='account_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounttype',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_account_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='max_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='min_amount',
            field=models.FloatField(),
        ),
    ]
