# Generated by Django 4.0.4 on 2024-01-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_id_number_alter_customuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agree',
            field=models.BooleanField(default=False),
        ),
    ]
